version: "3.8"
services:
  backend:
    build: ./backend
    container_name: chapter-editor-backend
    volumes:
      - ./backend/:/backend
    ports:
      - 5000

  nginx:
    build: ./nginx
    container_name: chapter-editor-frontend-nginx
    restart: always
    ports:
        - "80:80"
